version: "2"
services:
  blockchain:
    build: .
    expose:
      - "8545"
    ports:
      - "8545:8545"
    volumes_from:
      - blockchaindata
    working_dir: /opt/blockchain
    tty: true

  blockchaindata:
    image: tianon/true
    volumes:
      - .:/opt/blockchain
